apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concept
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paulodhiambo/concept.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: concept
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
